# Basic
edition    = "2024"
hard_tabs  = true
max_width  = 100
tab_spaces = 4

# Misc
match_block_trailing_comma = true
newline_style              = "Unix"
reorder_imports            = true
reorder_modules            = true
use_field_init_shorthand   = true
use_small_heuristics       = "Max"
