[workspace]
members  = ["src-tauri"]
resolver = "3"

[workspace.package]
authors     = ["Xavier Lau <x@acg.box>"]
description = "<DESCRIPTION>"
edition     = "2024"
homepage    = "https://hack.ink/<NAME>"
license     = "GPL-3.0"
readme      = "README.md"
repository  = "https://github.com/hack-ink/<NAME>"
version     = "0.1.0"

[profile.final-release]
inherits = "release"
lto      = true
