[package]
authors.workspace     = true
description.workspace = true
edition.workspace     = true
homepage.workspace    = true
license.workspace     = true
name                  = "rsnap-overlay"
readme.workspace      = true
repository.workspace  = true
version.workspace     = true

[lib]
path = "src/lib.rs"

[features]
cargo-clippy = []

[dependencies]
arboard           = { workspace = true }
color-eyre        = { workspace = true }
device_query      = { workspace = true }
egui              = { workspace = true }
egui-phosphor     = { workspace = true }
egui-wgpu         = { workspace = true }
egui-winit        = { workspace = true }
image             = { workspace = true }
pollster          = { workspace = true }
raw-window-handle = { workspace = true }
serde             = { workspace = true }
thiserror         = { workspace = true }
tracing           = { workspace = true }
wgpu              = { workspace = true }
winit             = { workspace = true }
xcap              = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
block2                   = { workspace = true }
objc                     = { workspace = true }
objc2                    = { workspace = true }
objc2-core-foundation    = { workspace = true }
objc2-core-graphics      = { workspace = true }
objc2-core-media         = { workspace = true }
objc2-core-video         = { workspace = true }
objc2-foundation         = { workspace = true }
objc2-screen-capture-kit = { workspace = true }
